# States for ConversationHandler
(
    SELECT_TYPE,
    INPUT_USER_NAME,
    INPUT_COUNT,
    POSITION_PHOTO,
    POSITION_NAME,
    POSITION_PRICE,
    INPUT_ORG,
    INPUT_CONTACT,
    SELECT_INDUSTRY,
    INPUT_RECIPIENT,
    SELECT_DATE,
    CONFIRM,
    INPUT_CUSTOM_DATE,
    INPUT_RECEIPT,
    SELECT_1C,
    CONFIRM_SUMMARY
) = range(16)
